CREATE DATABASE IF NOT EXISTS `gene_test`;
DROP TABLE IF EXISTS `gene_model_test`;

CREATE TABLE `gene_model_test` (
  `id`         INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name`       VARCHAR(100) COLLATE UTF8_UNICODE_CI NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;

